# Generated by Django 3.1 on 2021-04-20 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_id', models.UUIDField()),
                ('advisor_id', models.UUIDField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
